/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author aluno.saolucas
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();

        getContentPane().setBackground(new Color(255, 182, 193));
        lblResultado.setFont(new Font("Arial", Font.BOLD, 14));
        txtValor.setFont(new Font("Courier New", Font.PLAIN, 14));
        lblNome.setFont(new Font("Courier New", Font.PLAIN, 14));
        radioBtn1.setFont(new Font("Courier New", Font.PLAIN, 14));
        radioBtn2.setFont(new Font("Courier New", Font.PLAIN, 14));
        btnConverter.setFont(new Font("Courier New", Font.PLAIN, 14));
        btnConverter.setForeground(new Color(255, 110, 178));
        lblNome.setForeground(new Color(255, 110, 178));
        radioBtn1.setForeground(new Color(255, 110, 178));
        radioBtn2.setForeground(new Color(255, 110, 178));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btnConverter = new javax.swing.JButton();
        radioBtn1 = new javax.swing.JRadioButton();
        radioBtn2 = new javax.swing.JRadioButton();
        lblResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblNome.setText("^• ˕ •^ Temperatura:");

        btnConverter.setText("Converter");
        btnConverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConverterActionPerformed(evt);
            }
        });

        radioBtn1.setText("°C & °F");
        radioBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtn1ActionPerformed(evt);
            }
        });

        radioBtn2.setText("°F & °C ");
        radioBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(lblNome)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioBtn1)
                    .addComponent(radioBtn2)
                    .addComponent(btnConverter)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblResultado)
                .addGap(234, 234, 234))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(radioBtn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioBtn2)
                .addGap(15, 15, 15)
                .addComponent(btnConverter)
                .addGap(18, 18, 18)
                .addComponent(lblResultado)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void radioBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtn1ActionPerformed
        if (radioBtn1.isSelected()) {
            radioBtn2.setSelected(false);
        }
    }//GEN-LAST:event_radioBtn1ActionPerformed

    private void radioBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtn2ActionPerformed
        if (radioBtn2.isSelected()) {
            radioBtn1.setSelected(false);
        }
    }//GEN-LAST:event_radioBtn2ActionPerformed

    private void btnConverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConverterActionPerformed
        double valor = Double.parseDouble(txtValor.getText());

        ConversorTemperatura c1 = new ConversorTemperatura((int) valor);
        ConversorTemperatura c2 = new ConversorTemperatura(valor);
        String resultado = "";
        String clima = "";
        if (radioBtn1.isSelected()) {
            double temperaturaFahrenheit = (valor * 9 / 5) + 32;
            clima = c2.getTipoClima();
            resultado = "Temperatura: " + temperaturaFahrenheit + "°F\n" + clima;
        } else {
            double temperaturaCelsius = (valor - 32) * 5 / 9;
            clima = c1.getTipoClima();
            resultado = "Temperatura: " + temperaturaCelsius + "°C\n" + clima;
        }

        lblResultado.setText(resultado);
        
        if (clima.contains("O clima é frio")) {
            lblResultado.setForeground(Color.blue);
        } else if (clima.contains("O clima é agradável")) {
            lblResultado.setForeground(Color.green);
        } else if (clima.contains("O clima é quente")) {
            lblResultado.setForeground(Color.orange);
        } else {
            lblResultado.setForeground(Color.red);
        }

        txtValor.setText("");

    }//GEN-LAST:event_btnConverterActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConverter;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JRadioButton radioBtn1;
    private javax.swing.JRadioButton radioBtn2;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
